/* eslint-disable no-tabs */
/* Amplify Params - DO NOT EDIT
	API_PIGGYBANKOFHAPPINESS_GRAPHQLAPIIDOUTPUT
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONGROUPTABLE_ARN
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONGROUPTABLE_NAME
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONPROGRAMTABLE_ARN
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONPROGRAMTABLE_NAME
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONREWARDTABLE_ARN
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONREWARDTABLE_NAME
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONTABLE_ARN
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONTABLE_NAME
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONTASKTABLE_ARN
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONTASKTABLE_NAME
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONTRANSACTIONTABLE_ARN
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONTRANSACTIONTABLE_NAME
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONUSERTABLE_ARN
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONUSERTABLE_NAME
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONUSERTASKTABLE_ARN
	API_PIGGYBANKOFHAPPINESS_ORGANIZATIONUSERTASKTABLE_NAME
	ENV
	REGION
Amplify Params - DO NOT EDIT */

const resolvers = require('./resolvers');

exports.handler = async (event) => {
  console.log(event);
  const { typeName, fieldName } = event;
  const typeHandler = resolvers[typeName];
  if (typeHandler) {
    const resolver = typeHandler[fieldName];
    if (resolver) {
      try {
        return resolver(event);
      } catch (e) {
        console.log(e);
        throw new Error(e);
      }
    }
  }
  throw new Error(`Resolver ${typeName}/${fieldName} not found.`);
};
